version: '3.4'

services:
  jenkins-slave:
    image: ${REGISTRY}/jenkins-slave:${VERSION}
    configs:
      - source: pipeline-jobs
        target: /jobs.yaml
      - source: pipeline-config
        target: /config.yaml
    environment:
      SLAVE_NAME: "{{.Service.Name}}-{{.Task.Slot}}"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.labels.jenkins-slave == true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-workspaces:/workspaces
      - jenkins-ssh-settings:/etc/ssh
    networks:
      - pipeline
  jenkins:
    image: ${REGISTRY}/jenkins:${VERSION}
    ports:
      - "80:8080"
    configs:
      - source: pipeline-jobs
        target: /jobs.yaml
      - source: pipeline-config
        target: /config.yaml
    environment:
      JENKINS_SLAVES: jenkins-slave-1,jenkins-slave-2
      DOCKER_HOST: tcp://eid-jenkins02.dmz.local:2376
    deploy:
      placement:
        constraints:
          - node.labels.jenkins-master == true
    secrets:
      - source: ssh.git.difi.local
        target: ssh.git.difi.local
      - source: ssh.github.com
        target: ssh.github.com
      - source: artifactory_username
        target: artifactory_username
      - source: artifactory_password
        target: artifactory_password
      - source: artifactory-cleaner
        target: artifactory-cleaner
      - source: crucible_username
        target: crucible_username
      - source: crucible_password
        target: crucible_password
      - source: nexus_username
        target: nexus_username
      - source: nexus_password
        target: nexus_password
      - source: jira_username
        target: jira_username
      - source: jira_password
        target: jira_password
      - source: aws_username
        target: aws_username
      - source: aws_password
        target: aws_password
      - source: dockerHub_username
        target: dockerHub_username
      - source: dockerHub_password
        target: dockerHub_password
      - source: gitlab-api
        target: gitlab-api
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-workspaces:/workspaces
      - jenkins-builds:/builds
      - jenkins-ssh-settings:/etc/ssh
    networks:
      pipeline:
  polling-agent:
    image: ${REGISTRY}/polling-agent:${VERSION}
    secrets:
      - source: jira_username
        target: jira.username
      - source: jira_password
        target: jira.password
    volumes:
      - polling-job-repository:/data
    networks:
      - pipeline
    deploy:
      placement:
        constraints:
          - node.labels.jenkins-master == true
  nexus:
    image: ${REGISTRY}/nexus:${VERSION}
    ports:
      - "8080:8081"
      - "8081:8082"
      - "8082:8083"
      - "8083:8084"
    volumes:
      - nexus-data-new:/nexus-data
    networks:
      - pipeline
    deploy:
      placement:
        constraints:
          - node.labels.nexus == true

volumes:
  nexus-data-new:
    external: true
  jenkins-data:
    external: true
  jenkins-workspaces:
    external: true
  jenkins-builds:
    external: true
  jenkins-ssh-settings:
    external: true
  polling-job-repository:
    external: true

configs:
  pipeline-jobs:
    external: true
  pipeline-config:
    external: true

networks:
  pipeline:
    driver: overlay
    attachable: true

secrets:
  ssh.git.difi.local:
    external: true
  ssh.github.com:
    external: true
  artifactory-cleaner:
    external: true
  artifactory_username:
    external: true
  artifactory_password:
    external: true
  crucible_username:
    external: true
  crucible_password:
    external: true
  nexus_username:
    external: true
  nexus_password:
    external: true
  jira_username:
    external: true
  jira_password:
    external: true
  aws_username:
    external: true
  aws_password:
    external: true
  dockerHub_username:
    external: true
  dockerHub_password:
    external: true
  gitlab-api:
    external: true